### ISSUE TITLE
Autoupdate fails if app is logged in

### ISSUE THREAD

**Issue by nopap** [cern-phone-apps/desktop-phone-app#122]
**Describe the bug**
With the app logged in, autoupdate fails after asking to close the app. 

**To Reproduce**
1. Go to App -> Check for updates -> update available update now
2. Popup saying 'app will quit (please replace by close), press ok
3. App does not quit yet but asks to minimize or quit
4. App disappears (Crash)
5. Restarting the app, update was not done.
6. Doing the same, but with app not logged in works fine.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 18980
 - App Version 0.5.3 to 0.5.4 update

**Additional context**

**Comment by renefs** [comment]
We are aware of this bug. Please, logout and try the update from the login screen. It should work from there. (Issue #119)
