### ISSUE TITLE
The person on the other side of the line can't hear me

### ISSUE THREAD

**Issue by pferreir** [cern-phone-apps/desktop-phone-app#131]
**Describe the bug**
Whenever I receive/make a call, I can hear the other person but they cannot hear me.

**To Reproduce**
1. Dial a number using the dialpad
2. Click the green button
3. Speak

**Expected behavior**
The other person should hear my voice.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Mojave 10.14.6
 - App Version 0.5.4

**Additional context**
I checked that I have my headset set as "input device" on the app. I also checked that in the MacOS Sound settings there is indeed audio coming in.

![image](https://user-images.githubusercontent.com/2699/65438510-e47c0500-de25-11e9-9213-1fd9231310e3.png)

**Comment by renefs** [comment]
Tested with the phone app and with the desktop app. I wasn't able to hear @pferreir but he was hearing me perfectly. We need to do more tests since even with the Macbook default mic, it wasn't working.
