### ISSUE TITLE
Service accounts handling

### ISSUE THREAD

**Issue by tgbaron** [cern-phone-apps/desktop-phone-app#135]
When I log in with a service account, I don't see the shared numbers which are associated with the account, but I see those associated with the owner of the service account. that makes it impossible to use or configure numbers owned by service accounts. UCServices normally returns the correct list of numbers, so the error is somewhere else...
See for ex:
https://ucservices.web.cern.ch/api/listdialtonephonenumbers/indico
https://ucservices.web.cern.ch/api/listdialtonephonenumbers/tbaron

**Comment by renefs** [comment]
We must use usernames instead of person ids to provide support to this.

**Comment by renefs** [comment]
Created an issue in the backend
