### ISSUE TITLE
Icon in volume mixer not resized

### ISSUE THREAD

**Issue by lorys** [cern-phone-apps/desktop-phone-app#138]
When we open the volume mixer cern phone app icon is not the right size.
It's overflowing on volume setting level.

![IMG_20190927_095325](https://user-images.githubusercontent.com/31002428/65752608-6c575d00-e10d-11e9-81aa-b5a3c36f94d8.jpg)

And i found this:
https://github.com/vector-im/riot-web/pull/4183/commits/25a0af6ddbee0df6fb907aab3c7d9aa33ecd530c

**Comment by renefs** [comment]
It good looks to me on version `0.5.6`. We can open this issue again if this happens again in the future.

![mixer-looks-good](https://user-images.githubusercontent.com/1094547/66902616-3e28b700-f001-11e9-89d7-241fe6ac8606.PNG)
