### ISSUE TITLE
Not Able to install the AppImage

### ISSUE THREAD

**Issue by rikirenz** [cern-phone-apps/desktop-phone-app#141]
**Describe the bug**
I am not able to install the application on Linux CERN CentOS 7

**To Reproduce**
1. Download the package: `cern-phone-app-0.5.4-x86_64-linux.AppImage`
2. Make it executable
3. Run it using: `./cern-phone-app-0.5.4-x86_64-linux.AppImage    `
4. And you get this error:
```
[3385:1001/094549.397285:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/rcandido/.mount_cern-pBp3Bst/chrome-sandbox is owned by root and has mode 4755.
[1]    3385 trace trap (core dumped)  ./cern-phone-app-0.5.4-x86_64-linux.AppImage
```

**Expected behavior**
I should be able to install it

**Desktop (please complete the following information):**
 - OS: CentOS Linux 
 - Version: 7.5.1804 (Core) 
 - App Version: cern-phone-app-0.5.4-x86_64-linux

**Additional context**
- I have tried to give full access to the file using `chmod 777 cern-phone-app-0.5.4-x86_64-linux.AppImage`
- I have tried to run it using SUDO
- I follow this tutorial because I did not know this application format: https://itsfoss.com/use-appimage-linux/

**Comment by probonopd** [comment]
What happens if you start it with `./cern-phone-app-0.5.4-x86_64-linux.AppImage --no-sandbox`?

**Comment by renefs** [comment]
We've just made some tests and with `./cern-phone-app-0.5.4-x86_64-linux.AppImage --no-sandbox` should work fine. It is a workaround, not a perfect solution, but we need to investigate more here. In fact, in Ubuntu works fine, so our guess is that is something related with the OS

**Comment by probonopd** [comment]
Yes, many systems including Ubuntu set `sudo sysctl kernel.unprivileged_userns_clone=1` by default. As a result, the Chrome sandbox does not need root privileges on those systems.

**Comment by probonopd** [comment]
If you want to go the `--no-sandbox` route, you can use a custom AppRun bash script inside the AppImage that would call the main executable with `--no-sandbox` so that the user does not have to.

**Comment by renefs** [comment]
@probonopd I'm not very familiar with this kind of things. Do you have any examples of how can this be done?

**Comment by probonopd** [comment]
# Download AppImage and appimagetool and make them executable
wget -c "https://github.com/cern-phone-apps/desktop-phone-app/releases/download/v0.5.4/cern-phone-app-0.5.4-x86_64-linux.AppImage"
wget -c "https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage"
chmod +x *.AppImage

# Extract the AppImage in order to be able to edit its contents
./cern-phone-app-0.5.4-x86_64-linux.AppImage --appimage-extract

# Patch the call in the bash script that executes the main application, add "--no-sandbox"
sed -i -e 's|"$BIN"|"$BIN" --no-sandbox|g' squashfs-root/AppRun

# Fix desktop file
sed -i -e 's|^Icon=.*|Icon=cern-phone-app|g'  squashfs-root/cern-phone-app.desktop

# Repack AppImage
./appimagetool-x86_64.AppImage squashfs-root/

# Verify that it runs
./CERN_Phone_App-x86_64.AppImage

**Comment by renefs** [comment]
Thank you @probonopd for your help. We are going to give it a try and check if we can implement this on our release workflow. My guess is that other Electron apps must be also doing this somehow

**Comment by renefs** [comment]
Currently we are trying to use Docker in order to patch and repack the application, but we are getting:

```bash
root@d26451a5bfa2:~# ./appimagetool-x86_64.AppImage squashfs-root/
fuse: device not found, try 'modprobe fuse' first

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage
if you run it with the --appimage-extract option.
See https://github.com/AppImage/AppImageKit/wiki/FUSE
for more information
open dir error: No such file or directory
```

So we are trying to fix this error. Once it's done, we will be able to repack the app and make it fully compatible with Centos 7 :)

**Comment by probonopd** [comment]
Is FUSE working on your system, and is it enabled for your user?

On CentOS/RHEL:

```
user="$(whoami)"
usermod -a -G fuse "$user" 
```

Reference:
https://github.com/AppImage/AppImageKit/wiki/FUSE

**Comment by probonopd** [comment]
You did read the linked page, did you? ;-)

When running an AppImage from a Docker container you will get the following error:
```
fuse: failed to open /dev/fuse: Operation not permitted
Could not mount AppImage
Please see https://github.com/probonopd/AppImageKit/wiki/FUSE
```

You'll often hear "oh, just add these arguments to `docker run`
`--cap-add SYS_ADMIN --cap-add MKNOD --device /dev/fuse:mrw` and it'll work", but that is **totally insecure** and **not recommended**, as it **bypasses security restrictions which have been implemented for very good reasons**.

Instead, just extract the AppImage in your build script:

```
[...]
./appimagetool-*.AppImage --appimage-extract
# AppImage contents have been extracted to a directory called squashfs-root, which might be changed in the 
squashfs-root/AppRun <any argument that you'd normally pass directly to appimagetool-*.AppImage>
# clean up a bit
rm -rf squashfs-root/
[...]
```

Note: `appimagetool-*.AppImage` can be extracted starting with [release version 9](https://github.com/AppImage/AppImageKit/releases/tag/9)

If you want to decide whether to use the AppImage directly or extracted depending on whether you're in a container or not, for example in a build script, you can combine this with some [detection code](https://stackoverflow.com/a/23575107).
