### ISSUE TITLE
Make "Minimize to tray" the default close behavior

### ISSUE THREAD

**Issue by ThiefMaster** [cern-phone-apps/desktop-phone-app#145]
Right now there is this prompt when using the "close" button of the window on Windows: 

![image](https://user-images.githubusercontent.com/179599/65952728-c4aa9980-e442-11e9-8868-5d4d17c76d25.png)

However, for applications that people generally want to keep running in the background the most common behavior is to (this is the case with Skype, Discord, etc. for example):

- always "quit" to the tray
- have a context menu on the tray button to exit (in addition to the App->Quit menu)
- possibly have setting whether to quit to the tray or exit when using the window's button

**Comment by ThiefMaster** [comment]
Also, this balloontip is pretty annoying after you've seen it once:

![image](https://user-images.githubusercontent.com/179599/65977050-837dae00-e471-11e9-8727-f34549d59ce4.png)

**Comment by lnielsen** [comment]
The behaviour is the same on Mac and is counter-intuitive to me.  I agree with @ThiefMaster 

- Always quit to tray
- Add a context menu with a quit option.

![Screenshot 2019-10-15 at 10 19 14](https://user-images.githubusercontent.com/1698163/66813632-65b24d80-ef35-11e9-99dd-0f046e87d189.png)

In addition, when the app is minimized to tray, and I click the dock icon, the app doesn't appear. I have to click the tray icon to make it appear.

I would either:
1) Not have a dock icon (similar to what CERNBox etc is doing)
2) or, have a dock icon and show the app window when I click it.

![Screenshot 2019-10-15 at 10 22 55](https://user-images.githubusercontent.com/1698163/66813811-c2ae0380-ef35-11e9-8027-e971d9238547.png)
