### ISSUE TITLE
Detect no internet connection

### ISSUE THREAD

**Issue by lorys** [cern-phone-apps/desktop-phone-app#166]
If we don't have any internet connection we are landing on a blank page when we try to login.
We need to put an error message to inform the user that there are no internet connection (from the application).

- [x] Verify why the login screen pops up sometimes when there is no internet connection.
- [x] Display a banner when there is no internet connection
- [x] Improve the error messages when there is no internet connection

**Comment by renefs** [comment]
> "the phone app window just popped up with the "sign in" page
I think it'd be better if network issues showed a "no connection" error (possibly with a "loading" indicator preventing you from interacting with the app), instead of logging you our (or pretending you are logged-out)"
