### ISSUE TITLE
Pop-up doesn't disappear

### ISSUE THREAD

**Issue by TimSmithCH** [cern-phone-apps/desktop-phone-app#174]
When the call connects, the dial pop-up doesn't always disappear, so you can't see the hang-u button!
![Screenshot 2019-10-11 at 10 54 37 ](https://user-images.githubusercontent.com/7299592/66639449-245d2d80-ec17-11e9-9e3f-45cad80c4370.png)

To reproduce: seems to be most frequently the first call after login

**Comment by renefs** [comment]
I see, this happens when the call is done from the recent calls list
