### ISSUE TITLE
Determine how to link CERN Phone App users to Mattermost Users

### ISSUE THREAD

**Issue by renefs** [cern-phone-apps/desktop-phone-app#193]
Mattermost format:
- `https://mattermost.web.cern.ch/<team>/messages/@<username>`

Ex:
- `https://mattermost.web.cern.ch/it-dep/messages/@<username>`

**Comment by Fiser12** [comment]
We have talked with those responsible for Mattermost and they will incorporate a service that solves the route based on the username
